version: "3.7"
services:
  app:
    build: 
      args: 
        user: franver
        uid: 1000
      context: ./.docker
      dockerfile: Dockerfile
    image: laravelapp
    container_name: laravelapp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www:rw
      - ./.docker/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - laravelapp

  db:
    image: mysql:8
    ports:
      - "127.0.0.1:3306:3306"
    container_name: laravelapp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'libraries'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'libraries'
      MYSQL_USER: 'libraries_user'
    volumes:
      - ~/.mysql:/var/lib/mysql:rw
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravelapp

  nginx:
    image: nginx:1.17-alpine
    container_name: laravelapp-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src:/var/www:rw
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - laravelapp

networks: 
  laravelapp:
    driver: bridge